<?php

namespace comicvisorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * comicTieneCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comicTieneCategoriaRepository extends EntityRepository
{
}
