<?php

namespace comicvisorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * usuarioVotaComicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuarioVotaComicRepository extends EntityRepository
{
}
