<?php

namespace comicvisorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * usuarioSigueComicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuarioSigueComicRepository extends EntityRepository
{
}
