comicvisorBundle\Entity\categoria:
    type: entity
    table: null
    repositoryClass: comicvisorBundle\Repository\categoriaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tipo:
            type: string
            length: '200'
        descripcion:
            type: string
            length: '200'
    lifecycleCallbacks: {  }
