comicvisorBundle\Entity\usuarioVotaComic:
    type: entity
    table: null
    repositoryClass: comicvisorBundle\Repository\usuarioVotaComicRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idusuario:
            type: integer
        idcomic:
            type: integer
        voto:
            type: integer
    lifecycleCallbacks: {  }
