comicvisorBundle\Entity\version:
    type: entity
    table: null
    repositoryClass: comicvisorBundle\Repository\versionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idcapitulo:
            type: integer
        idusuario:
            type: integer
        numeroPag:
            type: integer
            column: numero_pag
    lifecycleCallbacks: {  }
