<?php

/* ::plantilla1.html.twig */
class __TwigTemplate_0c7b2b8e6d8ac76858472d61fb3653c6381e3c02262e2dbc44fb2e25e7f0864c extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
            'title' => array($this, 'block_title'),
            'stylesheets' => array($this, 'block_stylesheets'),
            'body' => array($this, 'block_body'),
            'body2' => array($this, 'block_body2'),
            'scripts' => array($this, 'block_scripts'),
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 2
        echo " <!DOCTYPE html>
<html>
  <head> 
    <meta charset=\"utf-8\">
    <title>";
        // line 6
        $this->displayBlock('title', $context, $blocks);
        echo "</title>
    <meta name=\"description\" content=\"This was generated by the Codeply editor and responsive design playground.\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <meta name=\"generator\" content=\"Codeply\">


    ";
        // line 12
        $this->displayBlock('stylesheets', $context, $blocks);
        // line 18
        echo "  </head>
  <body class=\"bg-faded\">
    <!--<header id=\"first\">
    <div class=\"header-content\">
        <div class=\"inner\">
            <h2>What's New in Bootstrap 4?</h2>
            <h5 class=\"wow fadeIn text-normal\">A free, one-page theme to highlight the new features</h5>
            <h6 class=\"wow fadeIn text-normal\">Based on 4.0-alpha.2</h6>
            <hr>
            <a href=\"#one\" class=\"btn btn-primary-outline btn-xl page-scroll wow fadeInUp\">Get Started</a>
        </div>
    </div>
</header>-->
<nav id=\"topNav\" class=\"navbar navbar-default navbar-fixed-top\">
    <div class=\"container\">
        <button class=\"navbar-toggler hidden-md-up pull-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#cabecera\">
            <span class=\"ion-navicon-round\"></span>
        </button>
        
        <a class=\"navbar-brand page-scroll titulo\" href=\"/web\">ComicVisor</a>
        <div class=\"collapse navbar-toggleable-sm\" id=\"cabecera\">
            <ul class=\"nav navbar-nav\">
                <li class=\"nav-item\">
                    <a class=\"nav-link page-scroll\" href=\"#one\">Biblioteca</a>
                </li>
                <li class=\"nav-item\">
                    <a class=\"nav-link page-scroll\" href=\"#two\">Populares</a>
                </li>
                <li class=\"nav-item\">
                    <a class=\"nav-link page-scroll\" href=\"#three\"> Subida</a> 
                </li>
            </ul>
            <ul class=\"nav navbar-nav pull-xs-right\">
            <li class=\"nav-item\">
                  <li class=\"nav-item\">
                    <a class=\"nav-link page-scroll\" href=\"#three\"><span class=\"ion-person\"></span>  Iniciar sesión</a>
                </li>
             </li>
            </ul>
        </div>
    </div>
</nav>
<section>
       <div class=\"container wow fadeInUp\">
        <div class=\"row\">
         ";
        // line 63
        $this->displayBlock('body', $context, $blocks);
        // line 64
        echo "        </div>
        <div class=\"row margintop contenedorpr\">
         ";
        // line 66
        $this->displayBlock('body2', $context, $blocks);
        // line 67
        echo "        </div>
         
       </div> 
</section>

    <!--scripts loaded here-->
    ";
        // line 73
        $this->displayBlock('scripts', $context, $blocks);
        // line 74
        echo "    <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>
    <script src=\"//cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js\"></script>
    <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js\"></script>
    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>
    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js\"></script>
    <script src=\"js/scripts.js\"></script>
  </body>
</html>";
    }

    // line 6
    public function block_title($context, array $blocks = array())
    {
    }

    // line 12
    public function block_stylesheets($context, array $blocks = array())
    {
        // line 13
        echo "    <link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css\" />
    <link href=\"//cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css\" rel=\"stylesheet\" />
    <link rel=\"stylesheet\" href=\"//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\" />
    <link rel=\"stylesheet\" href=\"css/styles.css\" />
    ";
    }

    // line 63
    public function block_body($context, array $blocks = array())
    {
    }

    // line 66
    public function block_body2($context, array $blocks = array())
    {
    }

    // line 73
    public function block_scripts($context, array $blocks = array())
    {
    }

    public function getTemplateName()
    {
        return "::plantilla1.html.twig";
    }

    public function getDebugInfo()
    {
        return array (  143 => 73,  138 => 66,  133 => 63,  125 => 13,  122 => 12,  117 => 6,  106 => 74,  104 => 73,  96 => 67,  94 => 66,  90 => 64,  88 => 63,  41 => 18,  39 => 12,  30 => 6,  24 => 2,);
    }
}
/* {# app/Resources/views/base.html.twig #}*/
/*  <!DOCTYPE html>*/
/* <html>*/
/*   <head> */
/*     <meta charset="utf-8">*/
/*     <title>{% block title %}{% endblock %}</title>*/
/*     <meta name="description" content="This was generated by the Codeply editor and responsive design playground." />*/
/*     <meta name="viewport" content="width=device-width, initial-scale=1.0">*/
/*     <meta name="generator" content="Codeply">*/
/* */
/* */
/*     {% block stylesheets %}*/
/*     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" />*/
/*     <link href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css" rel="stylesheet" />*/
/*     <link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />*/
/*     <link rel="stylesheet" href="css/styles.css" />*/
/*     {% endblock %}*/
/*   </head>*/
/*   <body class="bg-faded">*/
/*     <!--<header id="first">*/
/*     <div class="header-content">*/
/*         <div class="inner">*/
/*             <h2>What's New in Bootstrap 4?</h2>*/
/*             <h5 class="wow fadeIn text-normal">A free, one-page theme to highlight the new features</h5>*/
/*             <h6 class="wow fadeIn text-normal">Based on 4.0-alpha.2</h6>*/
/*             <hr>*/
/*             <a href="#one" class="btn btn-primary-outline btn-xl page-scroll wow fadeInUp">Get Started</a>*/
/*         </div>*/
/*     </div>*/
/* </header>-->*/
/* <nav id="topNav" class="navbar navbar-default navbar-fixed-top">*/
/*     <div class="container">*/
/*         <button class="navbar-toggler hidden-md-up pull-right" type="button" data-toggle="collapse" data-target="#cabecera">*/
/*             <span class="ion-navicon-round"></span>*/
/*         </button>*/
/*         */
/*         <a class="navbar-brand page-scroll titulo" href="/web">ComicVisor</a>*/
/*         <div class="collapse navbar-toggleable-sm" id="cabecera">*/
/*             <ul class="nav navbar-nav">*/
/*                 <li class="nav-item">*/
/*                     <a class="nav-link page-scroll" href="#one">Biblioteca</a>*/
/*                 </li>*/
/*                 <li class="nav-item">*/
/*                     <a class="nav-link page-scroll" href="#two">Populares</a>*/
/*                 </li>*/
/*                 <li class="nav-item">*/
/*                     <a class="nav-link page-scroll" href="#three"> Subida</a> */
/*                 </li>*/
/*             </ul>*/
/*             <ul class="nav navbar-nav pull-xs-right">*/
/*             <li class="nav-item">*/
/*                   <li class="nav-item">*/
/*                     <a class="nav-link page-scroll" href="#three"><span class="ion-person"></span>  Iniciar sesión</a>*/
/*                 </li>*/
/*              </li>*/
/*             </ul>*/
/*         </div>*/
/*     </div>*/
/* </nav>*/
/* <section>*/
/*        <div class="container wow fadeInUp">*/
/*         <div class="row">*/
/*          {% block body %}{% endblock %}*/
/*         </div>*/
/*         <div class="row margintop contenedorpr">*/
/*          {% block body2 %}{% endblock %}*/
/*         </div>*/
/*          */
/*        </div> */
/* </section>*/
/* */
/*     <!--scripts loaded here-->*/
/*     {% block scripts %}{% endblock %}*/
/*     <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>*/
/*     <script src="//cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>*/
/*     <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>*/
/*     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>*/
/*     <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>*/
/*     <script src="js/scripts.js"></script>*/
/*   </body>*/
/* </html>*/
