comicvisor_homepage:
    path:     /
    defaults: { _controller: comicvisorBundle:Default:index }

comicvisor_bibliotecapage:
    path:     /biblioteca
    defaults: { _controller: comicvisorBundle:Default:biblioteca}

comicvisor_popularpage:
    path:     /populares
    defaults: { _controller: comicvisorBundle:Default:popular }

comicvisor_comicpage:
    path:     /{portadaNombre}
    defaults: { _controller: comicvisorBundle:Default:comic }

comicvisor_capitulopage:
    path:     /{portadaNombre}/{numero}
    defaults: { _controller: comicvisorBundle:Default:capitulo }

comicvisor_versionpage:
    path:     /{portadaNombre}/{numero}/{idversion}/{pagina}
    defaults: { _controller: comicvisorBundle:Default:version}
    requirements:
        pagina:  \d+

comicvisor_busquedacapage:
    path:     /{nombre}_{categoria1}_{categoria2}_{categoria3}_{filtro}_{orden}_{pagina}
    defaults: { _controller: comicvisorBundle:Default:biblioteca}