comicvisor_homepage:
    path:     /
    defaults: { _controller: comicvisorBundle:Default:index }

comicvisor_comicpage:
    path:     /{portadaNombre}
    defaults: { _controller: comicvisorBundle:Default:comic }

comicvisor_capitulopage:
    path:     /{portadaNombre}/{numero}
    defaults: { _controller: comicvisorBundle:Default:capitulo }

comicvisor_versionpage:
    path:     /{portadaNombre}/{numero}/{idversion}/{pagina}
    defaults: { _controller: comicvisorBundle:Default:version}
    requirements:
        pagina:  \d+